### ISSUE TITLE
Unable to access the model from offered site

### ISSUE THREAD

**Issue by Szy-Young** [mpskex/Convolutional-Pose-Machine-tf#11] opened 2019-02-25 08:59 UTC
Hello,
        Thanks for your sharing! However, the site offered for downloading your model seems to be unaccessible currently. Is it Okay for you to put them on Google or BaiduYun Drive? Thanks a lot!

**Comment by mpskex** [comment] 2019-02-25 09:12
Thanks for submitting issue to this repository.

I will fix the accessibility problem to the site, and I will provide an alternative download link as fast as I can. Please keep track with this issue.

**Comment by mpskex** [comment] 2019-04-28 08:09
You can find the pre-trained model in this issue #13

This issue is commonly caused by your environment setup, please check your tensorflow configuration. As this issue is no longer active, I will temporarily close this issue. You can re-open it at any time.

**Closed as completed by mpskex** 2019-04-28 08:09 UTC
