### ISSUE TITLE
Error when trainning. 

### ISSUE THREAD

**Issue by binhmuc** [mpskex/Convolutional-Pose-Machine-tf#12] opened 2019-03-29 14:24 UTC
I use my own data, but got this problem :(
[*]	Model Built
Traceback (most recent call last):
  File "trainCPM.py", line 38, in <module>
    model.train()
  File "../net/CPM.py", line 224, in train
    _train_batch = next(self.generator)
  File "../dataset/datagen_para_branch.py", line 59, in generator
    gen = self.datagen.generator(*args, **kwargs)
  File "../dataset/datagen.py", line 459, in generator
    return self._aux_generator(*args, **kwargs)
TypeError: _aux_generator() got an unexpected keyword argument 'norm'

**Comment by mpskex** [comment] 2019-04-28 08:11
This seems to be a bug in data generator. Plz give me some time to check it out.

**Comment by mpskex** [comment] 2019-12-18 15:58
Since the issue is not active for a long time, I will close the issue until new response is been added to this thread.

**Closed as completed by mpskex** 2019-12-18 15:58 UTC
