### ISSUE TITLE
报错 求指导

### ISSUE THREAD

**Issue by WeiAiFenDou** [mpskex/Convolutional-Pose-Machine-tf#4] opened 2018-08-16 08:32 UTC
您好！
      非常感谢你的分享！
     我是一个刚入门的小白。在运行您的程序 predict.py 时报错了。
if __name__=='__main__':
    img_names = ['test_pic.jpg']
    j = predict(img_names, 'model/model.ckpt-99.data-00000-of-00001', debug=True, is_name=True)
    print(j)

![image](https://user-images.githubusercontent.com/28751447/44197647-d0b99600-a171-11e8-92e5-39057ecc98fb.png)

请问下，是我的参数设置的哪里有问题吗？

**Comment by mpskex** [comment] 2018-08-16 08:39
你在载入的时候不需要给出后缀名
就类如“model.ckpt-99"即可

**Comment by WeiAiFenDou** [comment] 2018-08-16 09:54
![image](https://user-images.githubusercontent.com/28751447/44202102-a077f480-a17d-11e8-834a-faf5589974b0.png)

 我把下载的model解压出来，是三个文件，我把三个文件都放在model文件夹下。参数如图还是报错。。

**Comment by mpskex** [comment] 2018-08-16 09:56
你把错误截图发来。

**Comment by WeiAiFenDou** [comment] 2018-08-16 09:57
- PLACEHOLDER build finished!
[!]	Warning:	Pretrained model not loaded...Using initial value! name:  conv1_1
python3.6(8063,0x7fff8b385340) malloc: *** error for object 0x1108573e8: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug

**Comment by WeiAiFenDou** [comment] 2018-08-16 10:02
![image](https://user-images.githubusercontent.com/28751447/44202320-36138400-a17e-11e8-94f3-fa2158b44ce1.png)

我断点进去，就在红线框出来的那句报错了，报的错在console的红框里

**Comment by gouyinchao** [comment] 2019-03-19 09:46
hi,can you please send the model to 1046866485@qq.com ? Thank you!

**Comment by mpskex** [comment] 2019-03-19 12:38
Currently my site is unavailable. Please wait for an alternate download link.

**Comment by mpskex** [comment] 2019-04-28 08:12
> hi,can you please send the model to [1046866485@qq.com](mailto:1046866485@qq.com) ? Thank you!

You can find the model in issue#13

**Comment by mpskex** [comment] 2019-04-28 08:14
> ![image](https://user-images.githubusercontent.com/28751447/44202320-36138400-a17e-11e8-94f3-fa2158b44ce1.png)
> 
> 我断点进去，就在红线框出来的那句报错了，报的错在console的红框里

This issue is commonly caused by your environment setup, please check your tensorflow configuration. As this issue is no longer active, I will temporarily close this issue. You can re-open it at any time.

**Closed as completed by mpskex** 2019-04-28 08:14 UTC
